"""A small in-repo place index backing the fake providers.

It exists so the whole capture -> resolve -> map loop runs with no API key and
no network. A real provider returns the same `ResolvedPlace` shape.
"""

from __future__ import annotations

GAZETTEER: list[dict] = [
    {
        "provider_place_id": "gt-acatenango",
        "name": "Acatenango Volcano",
        "aliases": ["Volcán Acatenango", "Acatenango"],
        "lat": 14.5008,
        "lon": -90.8761,
        "category": "nature",
        "city": "Antigua",
        "country": "Guatemala",
        "address": "Acatenango, Chimaltenango, Guatemala",
        "website": "https://www.inguat.gob.gt/",
        "opening_hours": "Overnight hikes depart 09:00; summit push 04:00",
        "price_level": "$$",
    },
    {
        "provider_place_id": "gt-cerro-de-la-cruz",
        "name": "Cerro de la Cruz",
        "aliases": ["Hill of the Cross"],
        "lat": 14.5648,
        "lon": -90.7305,
        "category": "viewpoint",
        "city": "Antigua",
        "country": "Guatemala",
        "address": "Antigua Guatemala, Sacatepéquez",
        "opening_hours": "Mon-Sun 06:00-18:00",
        "price_level": "free",
    },
    {
        "provider_place_id": "gt-rainbow-cafe",
        "name": "Rainbow Café",
        "aliases": ["Rainbow Cafe Antigua"],
        "lat": 14.5570,
        "lon": -90.7345,
        "category": "cafe",
        "city": "Antigua",
        "country": "Guatemala",
        "address": "7a Avenida Sur 8, Antigua Guatemala",
        "phone": "+502 7832 1919",
        "website": "https://rainbowcafeantigua.example",
        "opening_hours": "Mon-Sun 08:00-22:00",
        "price_level": "$",
    },
    {
        "provider_place_id": "gt-tremendo-hostel",
        "name": "Tremendo Hostel",
        "aliases": ["Tremendo"],
        "lat": 14.5602,
        "lon": -90.7331,
        "category": "accommodation",
        "city": "Antigua",
        "country": "Guatemala",
        "address": "5a Calle Poniente, Antigua Guatemala",
        "website": "https://tremendo.example",
        "opening_hours": "Reception 24h",
        "price_level": "$",
    },
    {
        "provider_place_id": "gt-lake-atitlan",
        "name": "Lake Atitlán",
        "aliases": ["Lago de Atitlán", "Lake Atitlan"],
        "lat": 14.6907,
        "lon": -91.2025,
        "category": "nature",
        "city": "Panajachel",
        "country": "Guatemala",
        "address": "Sololá, Guatemala",
        "opening_hours": "Open access",
        "price_level": "free",
    },
    {
        "provider_place_id": "gt-san-marcos-la-laguna",
        "name": "San Marcos La Laguna",
        "aliases": ["San Marcos"],
        "lat": 14.7261,
        "lon": -91.2570,
        "category": "attraction",
        "city": "Sololá",
        "country": "Guatemala",
        "address": "San Marcos La Laguna, Sololá",
        "price_level": "$",
    },
    {
        "provider_place_id": "gt-semuc-champey",
        "name": "Semuc Champey",
        "aliases": ["Semuc"],
        "lat": 15.5342,
        "lon": -89.9647,
        "category": "nature",
        "city": "Lanquín",
        "country": "Guatemala",
        "address": "Lanquín, Alta Verapaz",
        "opening_hours": "Mon-Sun 06:00-18:00",
        "price_level": "$",
    },
    {
        "provider_place_id": "gt-tikal",
        "name": "Tikal National Park",
        "aliases": ["Tikal", "Parque Nacional Tikal"],
        "lat": 17.2220,
        "lon": -89.6237,
        "category": "attraction",
        "city": "Flores",
        "country": "Guatemala",
        "address": "Petén, Guatemala",
        "website": "https://tikalpark.example",
        "opening_hours": "Mon-Sun 06:00-18:00",
        "price_level": "$$",
    },
    {
        "provider_place_id": "mx-bacalar-lagoon",
        "name": "Bacalar Lagoon",
        "aliases": ["Laguna de Bacalar", "Lagoon of Seven Colours"],
        "lat": 18.6769,
        "lon": -88.3894,
        "category": "nature",
        "city": "Bacalar",
        "country": "Mexico",
        "address": "Bacalar, Quintana Roo",
        "opening_hours": "Open access",
        "price_level": "$",
    },
    {
        "provider_place_id": "mx-mercado-20-noviembre",
        "name": "Mercado 20 de Noviembre",
        "aliases": ["Smoke Alley", "Pasillo de Humo"],
        "lat": 17.0578,
        "lon": -96.7247,
        "category": "restaurant",
        "city": "Oaxaca",
        "country": "Mexico",
        "address": "20 de Noviembre, Centro, Oaxaca de Juárez",
        "opening_hours": "Mon-Sun 07:00-21:00",
        "price_level": "$",
    },
    {
        "provider_place_id": "mx-hierve-el-agua",
        "name": "Hierve el Agua",
        "aliases": [],
        "lat": 16.8661,
        "lon": -96.2760,
        "category": "nature",
        "city": "San Lorenzo Albarradas",
        "country": "Mexico",
        "address": "San Lorenzo Albarradas, Oaxaca",
        "opening_hours": "Mon-Sun 08:00-18:00",
        "price_level": "$",
    },
    {
        "provider_place_id": "co-la-ciudad-perdida",
        "name": "Ciudad Perdida",
        "aliases": ["Lost City", "Teyuna"],
        "lat": 11.0383,
        "lon": -73.9256,
        "category": "attraction",
        "city": "Santa Marta",
        "country": "Colombia",
        "address": "Sierra Nevada de Santa Marta",
        "opening_hours": "Guided treks only, 4-5 days",
        "price_level": "$$$",
    },
]

# Destinations the fake provider understands as route stops.
DESTINATION_HINTS: dict[str, tuple[float, float, str]] = {
    "antigua": (14.5586, -90.7295, "Guatemala"),
    "lake atitlán": (14.6907, -91.2025, "Guatemala"),
    "lake atitlan": (14.6907, -91.2025, "Guatemala"),
    "flores": (16.9280, -89.8920, "Guatemala"),
    "lanquín": (15.5750, -89.9800, "Guatemala"),
    "lanquin": (15.5750, -89.9800, "Guatemala"),
    "bacalar": (18.6769, -88.3894, "Mexico"),
    "oaxaca": (17.0732, -96.7266, "Mexico"),
    "santa marta": (11.2408, -74.1990, "Colombia"),
}
