import { defineRailway, project, service } from "railway/iac";

// Generated by `railway config migrate --service app`, then given back the
// build and restart settings the generator dropped, so this says everything
// railway.json says.
//
// Not live yet: the service keeps reading railway.json until
// `railway config migrate cutover` is run. Delete railway.json only after that.
// This repository manages only its own resources in the environment.
// See https://docs.railway.com/infrastructure-as-code#multi-repo-projects
export const partial = "app";

export default defineRailway(() => {
  const app = service("app", {
    build: {
      builder: "DOCKERFILE",
      dockerfilePath: "Dockerfile",
    },
    deploy: {
      restartPolicyType: "ON_FAILURE",
      restartPolicyMaxRetries: 3,
    },
    healthcheck: "/health",
    healthcheckTimeout: 120,
    replicas: 1,
  });
  return project("tripstash", {
    resources: [app],
  });
});
