import { defineRailway, preserve, project, service, volume } from "railway/iac";

// Generated by `railway config migrate --service app`, then given back the
// build and restart settings the generator dropped, so this says everything
// railway.json says.
//
// Not live yet: the service keeps reading railway.json until
// `railway config migrate cutover` is run. Delete railway.json only after that.
// This repository manages only its own resources in the environment.
// See https://docs.railway.com/infrastructure-as-code#multi-repo-projects
export const partial = "app";

export default defineRailway(() => {
  // The volume that holds the database and every upload. Declared so that
  // applying this file can never read as "the service has no volume" and
  // detach it - the trips live here, and the image's own disk is thrown away
  // on every deploy.
  const data = volume("app-volume", { region: "sfo", sizeMB: 5000 });
  const app = service("app", {
    build: {
      builder: "DOCKERFILE",
      dockerfilePath: "Dockerfile",
    },
    deploy: {
      restartPolicyType: "ON_FAILURE",
      restartPolicyMaxRetries: 3,
    },
    healthcheck: "/health",
    healthcheckTimeout: 120,
    replicas: 1,
    volumeMounts: { "/data": data },
    // Set in the dashboard and kept there: preserve() leaves each live value
    // alone without writing it here. Left out, applying this file would delete
    // them, and production refuses to start without its own secret key.
    variables: {
      TRIPSTASH_CORS_ORIGINS: preserve(),
      TRIPSTASH_SECRET_KEY: preserve(),
      TRIPSTASH_USER_EMAIL: preserve(),
      TRIPSTASH_USER_PASSWORD: preserve(),
    },
  });
  return project("tripstash", {
    resources: [app, data],
  });
});
